// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwrfuzxxdtovbtfvulhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cmZ1enh4ZHRvdmJ0ZnZ1bGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTk3NTgsImV4cCI6MjA3MDk3NTc1OH0.CjDM5JAv_ubUBusrPD6ToYVNahDDyowmdSrEHpYwS-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});